Arrows on links to show direction
creativecommons/cccatalog-dataviz pull request #20
Opened 2020-03-20 06:21 UTC by BharatNischal

Fixes #14 

## Description

Added arrows to the links to show direction of the links. The size of arrow has been selected such that the arrow is visible even in low zoom.
When the nodes are not hovered/highlighted main focus is given on text label and when the node is hovered/highlighted the main focus is given to arrow.

## Screenshots
**Without hovering**
![ice_screenshot_20200320-111929](https://user-images.githubusercontent.com/33544814/77140715-75aff980-6aa0-11ea-9b08-507328bdb8a9.png)

**On hovering**
![ice_screenshot_20200320-112005](https://user-images.githubusercontent.com/33544814/77140768-a728c500-6aa0-11ea-924c-0d02f71aff4b.png)

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

2020-03-20 06:22 UTC, BharatNischal commented
@soccerdroid  @mathemancer  Please Review this PR

2020-04-17 03:26 UTC, soccerdroid commented
Is there any workaround for the arrows covering the edges descriptions?

2020-04-17 08:46 UTC, BharatNischal commented
@soccerdroid  I have tried to fix this issue by replacing the '<' and '>' character in the link text with the link arrow and by adding some spaces in between the source and destination name with the help of some mathematics.
Its working fine for links having large font-size but the arrows are coinciding with the text in case of small fontsize. (Please have a look at the screenshots). So do you want me to stay with this approach and fix this issue for smaller font-size (probabily just making the arrow size as a function of font-size) or do I consider some other solution? For example changing the color combinations so that the link-text is visible even after hovering or highlighting of link.
Please give me your opinion.

**For normal font-size**
![ice_screenshot_20200417-140335](https://user-images.githubusercontent.com/33544814/79550326-d2a9ca00-80b5-11ea-8800-064a1ba50f56.png)

**For smaller font-size**
![ice_screenshot_20200417-140231](https://user-images.githubusercontent.com/33544814/79550427-efde9880-80b5-11ea-94a7-57536fd86e51.png)


> Is there any workaround for the arrows covering the edges descriptions?

2020-04-21 18:16 UTC, soccerdroid commented
> @soccerdroid I have tried to fix this issue by replacing the '<' and '>' character in the link text with the link arrow and by adding some spaces in between the source and destination name with the help of some mathematics.
> Its working fine for links having large font-size but the arrows are coinciding with the text in case of small fontsize. (Please have a look at the screenshots). So do you want me to stay with this approach and fix this issue for smaller font-size (probabily just making the arrow size as a function of font-size) or do I consider some other solution? For example changing the color combinations so that the link-text is visible even after hovering or highlighting of link.
> Please give me your opinion.
> 
> **For normal font-size**
> ![ice_screenshot_20200417-140335](https://user-images.githubusercontent.com/33544814/79550326-d2a9ca00-80b5-11ea-8800-064a1ba50f56.png)
> 
> **For smaller font-size**
> ![ice_screenshot_20200417-140231](https://user-images.githubusercontent.com/33544814/79550427-efde9880-80b5-11ea-94a7-57536fd86e51.png)
> 
> > Is there any workaround for the arrows covering the edges descriptions?

Let's try with the color combination you mention, you can attach the screenshots here as a comment as well.

2020-05-05 20:48 UTC, soccerdroid commented
Hi @BharatNischal ! Did you try the color combination?

2020-05-06 10:03 UTC, BharatNischal commented
> Hi @BharatNischal ! Did you try the color combination?

@soccerdroid  Soo sorry for the delay. I was a little busy but I will finish this within 2 days and will get back to you.

2020-05-07 07:33 UTC, BharatNischal commented
@soccerdroid  I tried with color combination but it did not worked. No matter what color I choose the arrows are always above the text. So I tried this new solution where I translate the arrows when they are highlighted. please see the screenshots.
Or we can just place the text above the edge at the start too.
![ice_screenshot_20200507-125438](https://user-images.githubusercontent.com/33544814/81266698-d56b5f80-9062-11ea-9700-805a355478fa.png)

![ice_screenshot_20200507-125536](https://user-images.githubusercontent.com/33544814/81266750-f03dd400-9062-11ea-9599-63cbda765bd3.png)
what you say?

2020-05-13 15:59 UTC, soccerdroid commented
Is there any way we can move the arrow as close as possible to the node? That could be one workaround. Another one could be to set a smaller arrow size for shorter edges (though maybe this is more complex, not sure if this is possible with the current library). How do the arrows look like for shorter edges with your last solution?

2020-05-13 18:32 UTC, subhamX commented
Hi @soccerdroid and @BharatNischal. I think we can use **linkDirectionalArrowRelPos** method provided by force-graph and set its value around **1**, to keep the arrow in close proximity to the node.

Please have a look at the snapshot (using 0.99).

![linkArrowPos](https://user-images.githubusercontent.com/43654114/81850095-1dafe380-9575-11ea-9ed8-d39edeffa2f0.PNG)

2020-05-14 20:30 UTC, soccerdroid commented
Thanks @subhamX , I think that could work. What do you say @BharatNischal ?

2020-05-25 07:57 UTC, BharatNischal commented
> Thanks @subhamX , I think that could work. What do you say @BharatNischal ?

Yes thats a good solution. Thanks @subhamX  for the help.
Actually I was taking a break from coding for a week. I will fix the issue soon

2020-05-27 05:46 UTC, BharatNischal commented
It seems that this PR is having a conflict because of some previously merged PRs . How can I resolve this?

2020-05-27 14:36 UTC, subhamX commented
@BharatNischal It seems that your branch `BharatNischal:directed-Edges` is not synchronized with `creativecommons:master`. I suggest you to follow these steps to synchronize and resolve conflicts. 

Make sure you are on `directed-Edges` branch.

```bash
# Add upstream URL
git remote add upstream git@github.com:creativecommons/cccatalog-dataviz.git
# Fetch Information
git fetch upstream
# Rebase with upstream/master i.e creativecommons:master
git rebase upstream/master
```
After these, you will be prompted with Merge Conflict. Open your text editor and perform necessary changes which fix the conflict. 
```bash
# Add the index.html file
git add index.html
# Continue the rebase
git rebase --continue
# Push your changes to origin/directed-Edges
git push origin/directed-Edges
```

Hope this helps!

2020-05-28 13:59 UTC, BharatNischal commented
@subhamX thanks for the help. Now the merge issue has resolved but it now shows 3 extra commits. Is it ok?

2020-06-01 21:52 UTC, soccerdroid requested changes

2020-06-01 21:52 UTC, soccerdroid commented on GSoC2019/src/index.html
> +      .linkDirectionalArrowRelPos(0.99)
These lines are duplicated

2020-06-01 21:57 UTC, soccerdroid commented
> @subhamX thanks for the help. Now the merge issue has resolved but it now shows 3 extra commits. Is it ok?

I think it isn't. Correct me if I am wrong, but you modified only one js file, right?

2020-06-02 10:45 UTC, BharatNischal commented
> > @subhamX thanks for the help. Now the merge issue has resolved but it now shows 3 extra commits. Is it ok?
> 
> I think it isn't. Correct me if I am wrong, but you modified only one js file, right?

Yes I just updated index.html
How can I remove the extra commits?

2020-06-02 11:48 UTC, subhamX commented
@BharatNischal,  the steps I had mentioned earlier for rebasing shouldn't create any extra merge commits or any commits since rebase should have taken fast-forward route. 

I think that `632157c` commit is redundant and was created after the rebase operation. [Duplicacy](https://github.com/creativecommons/cccatalog-dataviz/pull/20#discussion_r433510391) is because of this commit. You can consider removing it since all changes are already present in previous commits.

Another small thing. Merge commits should arise if you pull the branch (git pull) and there are some changes in the server which are not present locally. `f3b6c90` and `d2a1103` are because of this. In case you wish to reduce the number of commits consider squashing them.

2020-06-03 17:26 UTC, soccerdroid commented
Another option, and because it got kind of confusing this rebasing/merging operation, is that you create another branch from the master branch, and add your modified file here. I'm suggesting this because the changes are not long. Is this easier for you @BharatNischal ?

2020-06-05 12:18 UTC, BharatNischal commented
> Another option, and because it got kind of confusing this rebasing/merging operation, is that you create another branch from the master branch, and add your modified file here. I'm suggesting this because the changes are not long. Is this easier for you @BharatNischal ?

Ok sure it will be relatively easy to create a new branch

2020-06-05 12:48 UTC, BharatNischal commented
https://github.com/creativecommons/cccatalog-dataviz/pull/30#issue-428428436
This is the link to new PR

2020-06-05 16:13 UTC, soccerdroid commented
Closing this as #30 has been accepted and merged. Thanks @BharatNischal !

2020-06-05 16:13 UTC, closed without merging