Update README.md
creativecommons/cccatalog-dataviz pull request #41
Opened 2020-08-31 17:01 UTC by subhamX

## Description
The following PR updates the `README.md`.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2020-09-02 14:37 UTC, soccerdroid requested changes

2020-09-02 14:37 UTC, soccerdroid commented on README.md
> +The backend application is using Django, for which Python necessary. Python can be installed from [here](https://www.python.org/downloads/).
Add the version numbers we are using.

2020-09-02 14:37 UTC, soccerdroid commented on README.md
> +5. Now to start the database in a isolated container.
an*

2020-09-04 14:52 UTC, soccerdroid requested changes

2020-09-04 14:52 UTC, soccerdroid commented on README.md
> +
delete these empty lines

2020-09-04 14:55 UTC, soccerdroid requested changes

2020-09-04 14:55 UTC, soccerdroid commented on README.md
> +1. Make sure that the root directory contains `docker-compose.yml`. And ensure that `backend/.env` has file is updated and `MONGO_HOSTNAME` is set to `mongodb:27017`.
, and ensure that the `backend/.env` file is updated....

2020-09-04 14:57 UTC, soccerdroid commented
Please can you describe a bit the frontend and backend part? Maybe as a comment in the directory structure section.  For example:
Backend: django server which contains the API that feeds data to the visualization
Frontend: code that builds and render the visualization in the browser.

2020-09-04 19:45 UTC, subhamX commented
> Please can you describe a bit the frontend and backend parts? Maybe as a comment in the directory structure section. For example:
> Backend: django server which contains the API that feeds data to the visualization
> Frontend: code that builds and render the visualization in the browser.

That's a great idea. I have added a few lines in the `Directory Structure` section. Have a look at it.

2020-09-06 18:59 UTC, soccerdroid requested changes

2020-09-06 18:59 UTC, soccerdroid commented on README.md
> +1. Make sure that the root directory contains `docker-compose.yml`. And ensure that `backend/.env` has file is updated and `MONGO_HOSTNAME` is set to `mongodb:27017`.
please fix this typo

2020-09-06 20:42 UTC, soccerdroid approved these changes

2020-09-06 20:43 UTC, merged